/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.fatec;
import javafx.application.Application;

public class App {
    public static void main(String[] args) {
         Application.launch(PrincipalBoundary.class, args);
    }
}
