/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.fatec;

import edu.fatec.paciente.view.PacienteBoundary;
import javafx.application.Application;

public class App {
    public static void main(String[] args) {
         Application.launch(PacienteBoundary.class, args);
    }
}
